[build]
  command = "composer install && php artisan key:generate && php artisan migrate --force && npm ci && npm run prod"
  publish = "public"
  environment = { PHP_VERSION = "8.2" }

[[plugins]]
  package = "netlify-plugin-one"

    [plugins.inputs]
    port = 80
