build:
  command: "composer install && php artisan key:generate && php artisan migrate --force && npm ci && npm run"
  commandOrigin: config
  environment:
    - PHP_VERSION
  publish: /opt/build/repo/public
  publishOrigin: config
plugins:
  - inputs: {}
    origin: config
    package: netlify-plugin-lighthouse
